import { ethers } from "ethers";
import { savePrivateKeyToIndexedDB } from "../utils/cryptoBridge";

// 1. Pull the local variables securely from your Vite configurations
const BESU_RPC_URL =
  import.meta.env.VITE_BESU_RPC_URL || "http://127.0.0.1:8545";
const CONTRACT_ADDRESS =
  import.meta.env.VITE_CONTRACT_ADDRESS ||
  "0xa50a51c09a5c451C52BB714527E1974b686D8e77";
const SYSTEM_PRIVATE_KEY =
  import.meta.env.VITE_SYSTEM_PRIVATE_KEY ||
  "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63";

// 2. The Human-Readable ABI matching your Solidity contract layout
const CONTRACT_ABI = [
  "function registerMessageHash(bytes32 _hash) public",
  "function verifyMessageHash(bytes32 _hash) public view returns (bool, uint256, address)",
];

/**
 * Programmatically registers a SHA-256 hash to Hyperledger Besu with zero gas
 * @param messageHash The raw 64-character SHA-256 hex string generated by the client
 */
export async function logHashToBlockchain(
  messageHash: string,
): Promise<string> {
  try {
    // Standardize hash input formatting for Solidity bytes32 compliance
    const cleanHash = messageHash.startsWith("0x")
      ? messageHash
      : `0x${messageHash}`;

    // Establish a direct link to your running rootless Podman container
    const provider = new ethers.JsonRpcProvider(BESU_RPC_URL);

    // Initialize the system administrator signer to bypass the need for MetaMask
    const systemWallet = new ethers.Wallet(SYSTEM_PRIVATE_KEY, provider);

    // Instantiate your live local contract instance
    const contract = new ethers.Contract(
      CONTRACT_ADDRESS,
      CONTRACT_ABI,
      systemWallet,
    );

    console.log(`📡 Dispatching hash registration: ${cleanHash}`);

    // Call the contract method with zero gas pricing requirements
    const tx = await contract.registerMessageHash(cleanHash, {
      gasLimit: 500000,
      gasPrice: 0,
    });

    // Wait for block finality within the local genesis state
    const receipt = await tx.wait();
    console.log("🚀 Ledger updated! Transaction Hash:", receipt?.hash);

    return receipt?.hash || "";
  } catch (error) {
    console.error(
      "❌ Failed to log authentication hash to Hyperledger Besu:",
      error,
    );
    throw error;
  }
}

/**
 * Natively generates a secure asymmetric keypair inside the browser context
 * Returns the exportable public key string to anchor to the database profile
 */
export async function generateClientIdentityKeys(userId?: string): Promise<string> {
  if (!window.crypto || !window.crypto.subtle) {
    throw new Error("Web Crypto API is unavailable. Ensure your origin is running on http://localhost.");
  }

  // 1. Generate an asymmetric RSA-OAEP cryptographic engine block
  const keyPair = await window.crypto.subtle.generateKey(
    {
      name: "RSA-OAEP",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]), // Standard 65537 exponent configuration
      hash: "SHA-256",
    },
    true,
    ["encrypt", "decrypt"]
  );

  // 2. Export the public key as a portable string block format (SubjectPublicKeyInfo Base64)
  const exportedPublicRaw = await window.crypto.subtle.exportKey("spki", keyPair.publicKey);
  const base64PublicKey = btoa(String.fromCharCode(...new Uint8Array(exportedPublicRaw)));

  // 3. SECURELY save the Private Key into IndexedDB for the active user
  const targetUserId = userId || localStorage.getItem("qchat_active_user_id");
  if (targetUserId) {
    await savePrivateKeyToIndexedDB(targetUserId, keyPair.privateKey);
  }

  return base64PublicKey;
}
