/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getUserIndexNumber"
      | "getUserRole"
      | "getUserStaffId"
      | "recordHash"
      | "userIndexNumber"
      | "userStaffId"
      | "verifyHash"
      | "verifyUser"
      | "verifyUserWithIndex"
      | "verifyUserWithStaffId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MessageHashRecorded" | "UserVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUserIndexNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStaffId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordHash",
    values: [string, BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userIndexNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userStaffId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifyHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "verifyUser",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyUserWithIndex",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyUserWithStaffId",
    values: [AddressLike, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserIndexNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStaffId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userIndexNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userStaffId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyUserWithIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyUserWithStaffId",
    data: BytesLike
  ): Result;
}

export namespace MessageHashRecordedEvent {
  export type InputTuple = [
    messageId: string,
    messageHash: BytesLike,
    sender: AddressLike,
    receiver: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    messageHash: string,
    sender: string,
    receiver: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    messageId: string;
    messageHash: string;
    sender: string;
    receiver: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserVerifiedEvent {
  export type InputTuple = [
    userAddress: AddressLike,
    role: string,
    identifier: string
  ];
  export type OutputTuple = [
    userAddress: string,
    role: string,
    identifier: string
  ];
  export interface OutputObject {
    userAddress: string;
    role: string;
    identifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MessageVerifier;
  waitForDeployment(): Promise<this>;

  interface: MessageVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getUserIndexNumber: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  getUserRole: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  getUserStaffId: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  recordHash: TypedContractMethod<
    [
      messageId: string,
      messageHash: BytesLike,
      sender: AddressLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  userIndexNumber: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  userStaffId: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  verifyHash: TypedContractMethod<[messageId: string], [string], "view">;

  verifyUser: TypedContractMethod<
    [userAddress: AddressLike, role: string],
    [void],
    "nonpayable"
  >;

  verifyUserWithIndex: TypedContractMethod<
    [userAddress: AddressLike, role: string, indexNumber: string],
    [void],
    "nonpayable"
  >;

  verifyUserWithStaffId: TypedContractMethod<
    [userAddress: AddressLike, role: string, staffId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUserIndexNumber"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserStaffId"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "recordHash"
  ): TypedContractMethod<
    [
      messageId: string,
      messageHash: BytesLike,
      sender: AddressLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userIndexNumber"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "userStaffId"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<[messageId: string], [string], "view">;
  getFunction(
    nameOrSignature: "verifyUser"
  ): TypedContractMethod<
    [userAddress: AddressLike, role: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyUserWithIndex"
  ): TypedContractMethod<
    [userAddress: AddressLike, role: string, indexNumber: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyUserWithStaffId"
  ): TypedContractMethod<
    [userAddress: AddressLike, role: string, staffId: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MessageHashRecorded"
  ): TypedContractEvent<
    MessageHashRecordedEvent.InputTuple,
    MessageHashRecordedEvent.OutputTuple,
    MessageHashRecordedEvent.OutputObject
  >;
  getEvent(
    key: "UserVerified"
  ): TypedContractEvent<
    UserVerifiedEvent.InputTuple,
    UserVerifiedEvent.OutputTuple,
    UserVerifiedEvent.OutputObject
  >;

  filters: {
    "MessageHashRecorded(string,bytes32,address,address,uint256)": TypedContractEvent<
      MessageHashRecordedEvent.InputTuple,
      MessageHashRecordedEvent.OutputTuple,
      MessageHashRecordedEvent.OutputObject
    >;
    MessageHashRecorded: TypedContractEvent<
      MessageHashRecordedEvent.InputTuple,
      MessageHashRecordedEvent.OutputTuple,
      MessageHashRecordedEvent.OutputObject
    >;

    "UserVerified(address,string,string)": TypedContractEvent<
      UserVerifiedEvent.InputTuple,
      UserVerifiedEvent.OutputTuple,
      UserVerifiedEvent.OutputObject
    >;
    UserVerified: TypedContractEvent<
      UserVerifiedEvent.InputTuple,
      UserVerifiedEvent.OutputTuple,
      UserVerifiedEvent.OutputObject
    >;
  };
}
